version: "3.9"
   
services:
  db:
    container_name: sc-db
    image: postgres:13
    network_mode: bridge
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=changeme
    volumes:
      - ./startup.sql:/docker-entrypoint-initdb.d/startup.sql
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5421:5432
  web:
    container_name: sc-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
